### ISSUE TITLE
Data link not working

### ISSUE THREAD

**Issue by RuoyanLi2002** [mihaela-stoian/ConstrainedDGM#1]
Hello, I noticed that the link provided for downloading the data is no longer working. When I try to access the link, I receive the following error:

"The page you are looking for does not exist or has been removed."

Could you please update the link or provide an alternative method for accessing the data? Thank you for your help!

**Comment by mihaela-stoian** [comment]
Hello,

Thank you for spotting this!
We have now updated the links (alternatively, they can also be found on page 17 in the Appendix of our paper).
Please let us know if you have other questions.
